[package]
name = "rust-proj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
tokio = {version = "1.37.0", features = ["full"]}
rusqlite = {version = "0.31.0", features = ["bundled"]}
rand = "0.9.0-alpha.1"
serde = {version = "1.0.197", features = ["derive"]}